### ISSUE TITLE
App crashes when i use in RecyclerView Adapter

### ISSUE THREAD

**Issue by nejifresh** [rtoshiro/FullscreenVideoView#19] opened 2016-07-26 17:16 UTC
The video view loads perfectly in my app. But it crashes after about 10 seconds. Here's the error: 

  java.lang.NullPointerException
                                                                            at com.github.rtoshiro.view.video.FullscreenVideoView.surfaceCreated(FullscreenVideoView.java:176)
                                                                            at android.view.SurfaceView.updateWindow(SurfaceView.java:662)
                                                                            at android.view.SurfaceView.access$000(SurfaceView.java:90)
                                                                            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
                                                                            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2191)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by rtoshiro** [comment] 2016-07-26 17:20
Hi @nejifresh 
This RecyclerView has more than one line? 
Maybe the list is destroying the other instances of FullscreenVideoView?
Did you call reset() in some point?

**Comment by rtoshiro** [comment] 2016-08-09 15:24
Do you have a code example simulating this problem?

**Comment by rtoshiro** [comment] 2016-08-17 17:36
Well
I'm closing it due to lack of reference.
You can open again if you want to. 
Thx
Best

**Comment by huxaiphaer** [comment] 2016-11-29 10:56
Hello rtoshiro am experiencing this Error , when i try to Scroll my RecyclerView up and down.

```
  Process: pixsor.app.huzykamz.pixoradmin, PID: 23557
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.setDisplay(android.view.SurfaceHolder)' on a null object reference
                      at com.github.rtoshiro.view.video.FullscreenVideoView.surfaceCreated(FullscreenVideoView.java:176)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:948)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1974)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                      at android.view.Choreographer.doFrame(Choreographer.java:550)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:211)
                      at android.app.ActivityThread.main(ActivityThread.java:5389)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```




Below is my code Block , I made a method in the Viewholder Class:

```
`public void setVideo(final Context c, final String videoUrl){
            try {
                if (videoUrl!=null) {
                    try {
                        Uri videoUri = Uri.parse(videoUrl);
                        try {
                            videoLayout.setVideoURI(videoUri);
                            videoLayout.setTag(videoUrl);
                      
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    } catch (Exception e) {
                        System.out.println("Error :" + e);
                    }

                } else {
                    videoLayout.setVisibility(View.GONE);
                }
            }
            catch (Exception e){

            }


        }`
```


Below is How i load My RecyclerAdapter am Using FirebaseRecyclerAdapter
```



 @Override
    protected void onStart() {
        super.onStart();

        //checkUserExists();
       // mAuth.addAuthStateListener(mAuthLitsener);
try {
    FirebaseRecyclerAdapter<Posts, BlogViewHolder> firebaseRecyclerAdapter = new FirebaseRecyclerAdapter<Posts, BlogViewHolder>(Posts.class,
            R.layout.item_activity,
            BlogViewHolder.class,
            mDatabase) {
        @Override
        protected void populateViewHolder(BlogViewHolder viewHolder, final Posts model, final int position) {


           
                    viewHolder.setVideo(c, model.getEventVideo());
                   
           

        }
    };

    mRecyclerview.setAdapter(firebaseRecyclerAdapter);
}
catch (Exception ex){

    System.out.println("Error "+ ex);
}
    }

```

**Comment by rtoshiro** [comment] 2016-12-01 16:56
Hi @huxaiphaer 
So, the problem is the same. 
The problem here is that surface creation is an asynchronous process. So, when surface gets created and you have already scrolled the view, there is a problem.
I'm not with my computer right now but i would suggest trying to call reset() in each new view. 
As soon as I got the computer I'll take a look. I have already used it in RecyclerView, so I think I can help better.

**Comment by huxaiphaer** [comment] 2016-12-01 17:16
OK thanks man,  I have used reset too but seems not working,  maybe first reach at your computer 

Thanks man

Sent from my Sony Xperia™ smartphone

---- Toshiro wrote ----

**Comment by SaifulIslam123** [comment] 2016-12-14 05:53
Hello rtoshiro, i am facing  this Error , when i try to Scroll my RecyclerView up and down.

E/UncaughtException: java.lang.NullPointerException
                                                                                               at com.github.rtoshiro.view.video.FullscreenVideoView.surfaceCreated(FullscreenVideoView.java:176)
                                                                                               at android.view.SurfaceView.updateWindow(SurfaceView.java:662)
                                                                                               at android.view.SurfaceView.access$000(SurfaceView.java:90)
                                                                                               at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
                                                                                               at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2191)
                                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
                                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                                               at android.os.Handler.handleCallback(Handler.java:808)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                               at android.os.Looper.loop(Looper.java:193)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                                               at dalvik.system.NativeStart.main(Native Method)



Here is my code:

private void setViewforOnlyVideo(OnetoOneMessege onetoOneMessege, int position, View videoChatLayout,
                                     ImageView videoChatUserImageView, final FullscreenVideoLayout  videoView) {


        videoChatLayout.setVisibility(View.VISIBLE);
        setUserImage(onetoOneMessege, videoChatUserImageView);

       // mediaController = new MediaController(this);
        Uri uri = Uri.parse(onetoOneMessege.getContentDownloadUrl());
        videoView.setActivity(this);

        try {
            videoView.reset();
            videoView.setVideoURI(uri);

        } catch (IOException e) {
            e.printStackTrace();
        }


please give me a solution as soon as possible.  I am eagerly waiting for your reply.
Thank you and regards

**Comment by rtoshiro** [comment] 2016-12-15 00:01
Hi @huxaiphaer / @SaifulIslam123 
I have fix/updated the FFView and released a new pre-release version. I fixed some issues regards of using it with a RecyclerView.
Would you mind testing it?
To test a pre-release you need to add the repository in build.gradle:
```
allprojects {
  repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }
}
```
And then, use the SNAPSHOT version:
compile 'com.github.rtoshiro.fullscreenvideoview:fullscreenvideoview:1.1.3a-SNAPSHOT'

Thx
Best
T

**Comment by hongol** [comment] 2016-12-23 08:44
This 1.1.3a-SNAPSHOT build solve my issue that is something similar to this! Would love it if you make it official release

**Comment by rtoshiro** [comment] 2017-09-03 19:28
@hongol 
Ah, sorry but better late than never :)
New version released.

**Closed as completed by rtoshiro** 2017-09-03 19:28 UTC
